### ISSUE TITLE
CREATED time and RRULE (frequency)

### ISSUE THREAD

**Issue by megamorphg** [chrisblakley/Daylight-Calendar-ICS#6]
When I used it to export for 2021 year for my location, I noticed the ICS actually repeats for 3 years and has a created time from 2020.
Would it make sense to make the the frequency a parameter as well or just eliminate it? Because if I export for a specific year, I likely only want it for that year.
Not sure if the created time of 2020 matters at all.

```
BEGIN:VEVENT
**CREATED:20200101T000000Z**
DTSTART:20210101T150700Z
DTEND:20210102T005400Z
DTSTAMP:20211030T132158Z
LAST-MODIFIED:20200702T133055Z
UID:775dca008b9aa7d9fec50a4c5e77f5d5@gearside.com
DESCRIPTION:Daylight calendar by Gearside.com
URL;VALUE=URI:http://gearside.com/calendars/daylight.ics
SUMMARY: 9h 47m (40.8%) [1 Percentile]. Solar noon: 1:00pm. 
**RRULE:FREQ=YEARLY;COUNT=3**
END:VEVENT
```

**Comment by chrisblakley** [comment]
Ah yeah I hard-coded it to create events for the previous year, current year, and following year because in December and January there are certain calendar views that allow you to see a combination of years (ex: the week view during the last week of December where it shows a few days in January).

Probably not the most elegant solution to duplicate _all_ events like that, but it was the quick-fix option.

The `CREATED` time is a red-herring here and not causing the issue– it's definitely the `COUNT=3` part of that snippet.

I'm open to ideas– and a URL parameter for `?count=1` could certainly be an option here.

**Comment by megamorphg** [comment]
Ahh, thank for the explanation, I'll just use the direct URL mode rather than year specific calendar import.

For the year-specific calendar export though, it would be better just to export the year without repeats, I think because if person wanted the overlapping week, they could just export the next/previous year.
